---
#- name: get touch-device ID
#  shell:
#    cmd: ''
#  register: touch_device_listing

- set_fact:
    touch_device_id: 7 # touch_device_listing.stdout

- name: ensure .desktop application file exists
  template:
    src: pluslife.desktop.j2
    dest: /usr/share/applications/pluslife.desktop

- name: ensure application is in autostart
  file:
    path: /etc/xdg/autostart/pluslife.desktop
    src: /usr/share/applications/pluslife.desktop
    state: link

- name: deploy icon for the .desktop file
  copy:
    src: pluslife.png
    dest: /opt/pluslife.png

#- name: check if locally downloaded version of Pluslife Analyzer already exists on controller
#  delegate_to: localhost
#  stat:
#    path: "files/Pluslife Analyzer.html"
#  register: stat_html
#
#- debug: var=stat_html

- fail:
    msg: |
      The Pluslife Analyzer local copy was not found!
      Please visit https://virus.sucks/pluslife_app and press Ctrl+S to save the page.
      After that, copy the html and the _files directory to the files/ directory here.
  when: "lookup('ansible.builtin.fileglob', role_path + '/files/Pluslife Analyzer.html') == []"

- name: deploy offline version of the Pluslife Analyzer
  copy:
    src: "Pluslife Analyzer.html"
    dest: /opt/

- name: deploy offline version of the Pluslife Analyzer
  copy:
    src: "Pluslife Analyzer_files"
    dest: /opt/
