---
# condensed version of github.com/goodtft/LCD-Show/LCD35-show
- name: remove libinput.conf
  file:
    path: /etc/X11/xorg.conf.d/40-libinput.conf
    state: absent

- name: ensure path
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: copy the devicetree binary
  copy:
    src: tft35a-overlay.dtb
    dest: /boot/overlays/

- name: copy the devicetree binary as object
  copy:
    src: tft35a-overlay.dtb
    dest: /boot/overlays/tft35a.dtbo

- name: set options in boot-config.txt
  lineinfile:
    path: /boot/config.txt
    line: "{{ item }}"
  loop:
    - "hdmi_force_hotplug=1"
    - "dtparam=i2c_arm=on"
    - "dtparam=spi=on"
    - "enable_uart=1"
    - "dtoverlay=tft35a:rotate={{ pluslife.display_rotation }}"
    - "hdmi_group=2"
    - "hdmi_mode=1"
    - "hdmi_mode=87"
    - "hdmi_cvt 480 320 60 6 0 0 0"
    - "hdmi_drive=2"

- name: copy calibration.conf
  copy:
    src: 99-calibration.conf
    dest: /etc/X11/xorg.conf.d/99-calibration.conf

- name: copy fbturbo tuning
  copy:
    src: 99-fbturbo.conf
    dest: /usr/share/X11/xorg.conf.d/99-fbturbo.conf

# do? echo "gpio:resistance:35:90:480:320" > ./.have_installed

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 600
    name: ["cmake", "libraspberrypi-dev", "xserver-xorg-input-evdev"]

- name: check if rpi-fbcp is installed
  stat:
    path: /usr/local/bin/fbcp
  register: fbcp_result

- name: ensure rpi-fbcp installed
  block:
  - name: clone rpi-fbcp repo
    git:
      repo: "https://github.com/tasanakorn/rpi-fbcp"
      dest: "/opt/rpi-fbcp"
      force: yes

  - name: make build folder
    file:
      path: "/opt/rpi-fbcp/build"
      state: directory

  - name: make + install
    shell:
      cmd: "cmake .. && make && install fbcp /usr/local/bin/fbcp"
      chdir: /opt/rpi-fbcp/build

  - name: ensure fbcp autostart
    lineinfile:
      line: "sleep 7; fbcp &"
      insertbefore: "exit 0"
      path: /etc/rc.local

  when: "not fbcp_result.stat.exists"

# necessary to rename /usr/share/X11/xorg.conf.d/10-evdev.conf to 45-evdev.conf?

