---
- name: ensure hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- include_tasks: configure_chromium.yml
- include_tasks: configure_touchscreen.yml

- name: set hardware button
  lineinfile:
    line: "dtoverlay=gpio-key,gpio={{ pluslife.return_button_gpio }},keycode=28"
    path: /boot/config.txt

# todo: .xsession overwrites some autologin stuff. Wrong location. Where to instead for wayland?
#- name: ensure energy savings settings
#  lineinfile:
#    line: "xset -dpms"
#    create: yes
#    group: pi
#    owner: pi
#    path: /home/pi/.xsession
